#利用R语言打造量化分析平台
#具体利用quantmod包实现对股票的量化分析

#1.API读取在线行情
#加载quantmod包
if(!require(quantmod)){
	install.packages("quantmod")
}
#获取股票行情指数
Quote=function(code){
	index=match(code,universes)
	temp=lapply(universes,get)
	return(temp[[index]])
}
#基本配置
universes<<-c("000001.SZ","QIHU","MOMO")#以陌陌，360，A股的平安银行为例
from="2015-01-04"#开始时间
to=Sys.Date()#结束时间设为当前日期
src="yahoo"#来源雅虎财经

#行情加载
quantmod::getSymbols(universes,from=from,to=to,src=src)

#绘制行情信息
quantmod::chartSeries(Quote("MOMO"),up.col='red',dn.col='green',TA="addVo();addADX();addMACD();addSMA(n=10);addBBands(n=14,sd=2,draw=\"bands\")")

#2.利用CSV读取离线行情
#以平安银行为例
#加载zoo时间序列包
library(zoo)
library(quantmod)
#配置文件路径
filePath='/home/KANO/Rfile/temp.csv'
#读取CSV并转化时间格式
csv<-read.csv(filePath,header=TRUE,sep=",")
csv$LZ_GPA_QUOTE_TCLOSE<-as.POSIXct(as.character(csv$LZ_GPA_QUOTE_TCLOSE),tz="",format="%Y%m%d")
#转化为zoo类型
temp=read.zoo(csv)
#转化为xts类型
payh=as.xts(temp[,1]);colnames(payh)="Close"
#绘图
chartSeries(payh,name="000001.SZ")
#添加MACD曲线
addMACD()

#3.quantmod包指标函数名(使用只需要运行下列函数就能添加相关曲线)
#威尔斯怀尔德移动方向指标
addADX()
#真实波幅
addATR()
#布林通道
addBBands()
#布林带宽
addBBands()
#百分比布林带
addBBands()
#顺势指标
addCCI()
#资金流动
addCMF()
#钱德动量指标
addCMO()
#双指数移动平均
addDEMA()
#离势价格偏离指数
addDPO()
#指数平滑移动平均线
addEMA()
#价格信封
addEnvelope()
#指数量权移动平均线
addEVWMA()
#期权期货到期
addExpiry()
#异同平均线
addMACD()
#动量
addMomentum()
#变动率
addROC()
#相对强弱指数
addRSI()
#转折点信号
addSAR()
#简单移动平均线
addSMA()
#随机动量指数
addSMI()
#三重平滑振荡指数
addTRIX()
#成交量
addVo()
#加权移动平均法
addWMA()
#零延迟指数移动平均线
addZLEMA()

